djangoproject/GoodReads/Books/urls.py
from django.conf.urls import include, url
from django.urls import path, re_path
from Books import views
from django.views.generic import ListView,TemplateView
from . import views

app_name ='Books'

urlpatterns = [
     url(r'^users/(?P<user_id>[0-9]+)/$', views.users),
    re_path('^search/$',views.search,name='search'),
    path('Books/Author/', views.allauthors, name='allauthors'),
    path('Books/Books/', views.allbooks, name='allbooks'),
    url(r'^Books/Books/(?P<number>[0-9])+/$',views.publicBook,name='bookForAll'),
    url(r'^Books/Books/(?P<number>[0-9])+/(?P<user_id>[0-9])+/$',views.book,name='book'),
	#url(r'^Books/Books/(?P<number>[0-9])+/$',views.book,name='book'),
	url(r'^Books/Books/category/(?P<categoryId>[0-9])+/$',views.categories,name='categories'),
    url(r'^Books/(?P<author_id>[0-9]+)/$', views.authordetail, name='authordetail'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<user_id>)/$',views.login,name='myurl'),
    url(r'^Books/(?P<author_id>[0-9]+)/favorite$', views.favorite, name='favorite'),
	
]

djangoproject/GoodReads/GoodReads/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('', include('Books.urls')),
    url('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoproject/GoodReads/Books/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to="users", null=True, blank=True)
    
    def __str__(self):
        return self.user.username

class author(models.Model):
    name = models.CharField(max_length=250)
    date_of_birth = models.CharField(max_length=250)
    nationality = models.CharField(max_length=50)
    gender = models.CharField(max_length=10)
    picture = models.ImageField(upload_to="authors", null=True, blank=True)
    is_followed=models.BooleanField(default=False)


    def __str__(self):
        return self.name

class books(models.Model):
    users = models.ManyToManyField('Profile', through='book_user')
    author_id = models.ForeignKey(author, on_delete=models.CASCADE)

    name = models.CharField(max_length=500)
    type = models.CharField(max_length=100)
    picture = models.ImageField(upload_to="books", null=True, blank=True)
    summary = models.CharField(max_length=500)
    is_favorite=models.BooleanField(default=False)


    def __str__(self):
        return self.name

class category(models.Model):
    Books = models.ManyToManyField('books')

    type = models.CharField(max_length=100)


    def __str__(self):
        return self.type

class book_user(models.Model):
    Book = models.ForeignKey(books, on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)

    review = models.CharField(max_length=500)
    rate = models.CharField(max_length=500)
    status = models.CharField(max_length=500)

    def __str__(self):
        return self.user

djangoproject/GoodReads/Books/forms.py
from django import forms

class LoginForm(forms.Form):
	user=forms.CharField(max_length=100)
	password=forms.CharField(widget=forms.PasswordInput())
	

djangoproject/GoodReads/Books/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404,redirect ,redirect
from Books.models import *
from Books.forms import LoginForm

def index(request):
    #return HttpResponse("<h1> this is Books HomePage")
    return render(request, 'startUpPage.html' ,{})

def login(request,user_id):
	username=""
	if request.method=="POST":
		MyLoginForm=LoginForm(request.POST)
		username=request.POST.get('username')
		password=request.POST.get('password')
		
	users=User.objects.filter()
	
	for user in users:
		
		if user.username==username and user.check_password(password):
			
			return render(request,'users.html',{"user":user,"books":{}})	
	return render(request,'startUpPage.html',{})	
	

	
def users(request,user_id):
    # user = Profile.objects.get(user=request.user.id)
    user = Profile.objects.get(pk=user_id)
    booksReview = book_user.objects.filter(pk=user_id)
    books = [book.Book for book in booksReview]

    for i in range(len(books)):
        books[i].review = booksReview[i].review
        books[i].rate = booksReview[i].rate
        books[i].status = booksReview[i].status

    return render(request, 'users.html/' ,{'books' : books, 'user' : user})


def search(request):
    if request.method == 'GET':
        searchText = request.GET.get("search")
        books_list = books.objects.filter(name__icontains=searchText)
        authors_list = author.objects.filter(name__icontains=searchText)
        return render(request,'search.html',{'books_list':books_list,'authors_list':authors_list})

def allauthors(request):
    all_authors=author.objects.all();
    return render(request,'allauthor.html',{'all_authors': all_authors ,})


def authordetail(request,author_id):
    bookss=books.objects.filter(author_id=author_id)
    authorr=get_object_or_404(author,pk=author_id)
    return render(request,'authordetails.html',{'author': authorr ,'bookss':bookss})



def favorite(request,author_id):
    authorr=get_object_or_404(author,pk=author_id)
    bookss=books.objects.filter(author_id=author_id)
    try:
        selected_book=books.objects.get(pk=request.POST['bookk'])
    except (KeyError,books.DoesNotExist):
        return render(request,'authordetails.html',{'author': authorr ,'bookss':bookss ,'error_message':"You did not select a valid book",})
    else:
        selected_book.is_favorite = True
        selected_book.save()
        return render(request,'authordetails.html',{'author': authorr,'bookss':bookss ,})


def allbooks(request):
    all_books=books.objects.all();
    return render(request,'allbooks.html',{'all_books': all_books ,})
def book(request,number,user_id):
	selectedBook=books.objects.get(id=number)
	users=book_user.objects.filter(user=user_id , Book=number)
	if users.count()==0:
		bookName=books.objects.get(id=number)
		userName=Profile.objects.get(user=user_id)
		user=book_user.objects.create(Book=bookName,user=userName,rate='0',status='Want to Read')
		
		users=book_user.objects.filter(user=user_id , Book=number)
		
	else:
		if request.method=="POST":
			for user in users:
				if request.POST.get('star'):
					user.rate=int(request.POST.get('star'))
				if request.POST.get('dropbtn'):
					user.status=request.POST.get('dropbtn')
				user.save()
				
	
	rate=[]
	status=[]
	for user in users:
		rate.append(int(user.rate))
		status.append(user.status)
	authors=author.objects.get(name=selectedBook.author_id)
	bookCategory=selectedBook.category_set.all()
	
	return render(request,'Books_page.html',{'selectedBook':selectedBook,'authors':authors,'bookCategory':bookCategory,'user_rate':rate,'user_status':status},)
def publicBook(request,number):
	selectedBook=books.objects.get(id=number)
	authors=author.objects.get(name=selectedBook.author_id)
	bookCategory=selectedBook.category_set.all()
	return render(request,'Books_page.html',{'selectedBook':selectedBook,'authors':authors,'bookCategory':bookCategory},)
def categories(request,categoryId):
	selectedBook=books.objects.all()
	selectedCategory=[]
	categoryName=""
	for book in selectedBook:
		for cat in book.category_set.all():
			if cat.id==int(categoryId):
				categoryName=cat
				selectedCategory.append(book)
	return render(request,'category.html',{'selectedCategory':selectedCategory,'categoryName':categoryName},)
	

djangoproject/GoodReads/Books/templates/Books_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body%}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/////font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "/css/Books_page.css" %}"/>
  <link rel="stylesheet" href="{% static "/css/Droplist.css" %}"/>
<div class="book">

<div>{{selectedBook.name}}</div>

<span><img src="/media/{{selectedBook.picture}}" class="bookimg"></img></span>

<span>Summary:{{selectedBook.summary}}<span>

</div>
<div>


</div>
<div class="Author" >Author:<a href="/Books/{{authors.id}}">{{selectedBook.author_id}}</a></div>
<p>Category:</p>
{% for cat in bookCategory %}
<div class="category" ><a href="/Books/Books/category/{{cat.id}}">{{cat}}</a></div>

</div>
{% endfor %}
<div class="dropdown">


{% if user_status.0 %}
<button class="dropbtn" >{{user_status.0}}</button>
{% else %}
<button class="dropbtn" >Want to Read</button>
{% endif %}
<div id="DropDownContent">
<form method="POST"> {% csrf_token %}

<input type="submit" value="Read" name="dropbtn" class="btn"/>
<input type="submit" value="Currently Read" name="dropbtn" class="btn"/>
<input type="submit" value="Want to Read" name="dropbtn" class="btn"/>
</form>
</div>
</div>

<div class="stars">
  <form id="stars_form" action="" method="POST"> {% csrf_token %}

{% if user_rate.0 == 5 %}
<input onchange='this.form.submit();' class="star star-5" id="star-5" value="5" type="radio" name="star" checked/>

    <label class="star star-5" for="star-5"></label>

    <input onchange='this.form.submit();' class="star star-4" id="star-4" value="4" type="radio" name="star" />

    <label class="star star-4" for="star-4"></label>

    <input onchange='this.form.submit();' class="star star-3" id="star-3" value="3" type="radio" name="star" />

    <labe class="star star-3" for="star-3"></label>

    <input onchange='this.form.submit();' class="star star-2" id="star-2" value="2" type="radio" name="star"  />
    <label class="star star-2" for="star-2"></label>

    <input onchange='this.form.submit();' class="star star-1" id="star-1" value="1" type="radio" name="star"/>

    <label class="star star-1" for="star-1"></label>
{% elif user_rate.0 == 4 %}
<input onchange='this.form.submit();' class="star star-5" id="star-5" value="5" type="radio" name="star"  />

    <label class="star star-5" for="star-5"></label>

<input onchange='this.form.submit();' class="star star-4" id="star-4" value="4" type="radio" name="star" checked/>

    <label class="star star-4" for="star-4"></label>

    <input onchange='this.form.submit();' class="star star-3" id="star-3" value="3" type="radio" name="star" />

    <label class="star star-3" for="star-3"></label>

    <input onchange='this.form.submit();' class="star star-2" id="star-2" value="2" type="radio" name="star"  />
    <label class="star star-2" for="star-2"></label>

    <input onchange='this.form.submit();' class="star star-1" id="star-1" value="1" type="radio" name="star" />

    <label class="star star-1" for="star-1"></label>
{% elif user_rate.0 == 3 %}
<input onchange='this.form.submit();' class="star star-5" id="star-5" value="5" type="radio" name="star"  />

    <label class="star star-5" for="star-5"></label>
<input onchange='this.form.submit();' class="star star-4" id="star-4" value="4" type="radio" name="star" />

    <label class="star star-4" for="star-4"></label>

    <input onchange='this.form.submit();' class="star star-3" id="star-3" value="3" type="radio" name="star" checked />

    <label class="star star-3" for="star-3"></label>

    <input onchange='this.form.submit();' class="star star-2" id="star-2" value="2" type="radio" name="star"  />
    <label class="star star-2" for="star-2"></label>

    <input onchange='this.form.submit();' class="star star-1" id="star-1" value="1" type="radio" name="star"/>

    <label class="star star-1" for="star-1"></label>
{% elif user_rate.0 == 2 %}
<input onchange='this.form.submit();' class="star star-5" id="star-5" value="5" type="radio" name="star"  />

    <label class="star star-5" for="star-5"></label>
<input onchange='this.form.submit();' class="star star-4" id="star-4" value="4" type="radio" name="star" />

    <label class="star star-4" for="star-4"></label>

    <input onchange='this.form.submit();' class="star star-3" id="star-3" value="3" type="radio" name="star" />

    <label class="star star-3" for="star-3"></label>

    <input onchange='this.form.submit();' class="star star-2" id="star-2" value="2" type="radio" name="star" checked />
    <label class="star star-2" for="star-2"></label>

    <input onchange='this.form.submit();' class="star star-1" id="star-1" value="1" type="radio" name="star" />

    <label class="star star-1" for="star-1"></label>
{% elif user_rate.0 == 1 %}
<input onchange='this.form.submit();' class="star star-5" id="star-5" value="5" type="radio" name="star"  />

    <label class="star star-5" for="star-5"></label>
<input onchange='this.form.submit();' class="star star-4" id="star-4" value="4" type="radio" name="star" />

    <label class="star star-4" for="star-4"></label>

    <input onchange='this.form.submit();' class="star star-3" id="star-3" value="3" type="radio" name="star" />

    <label class="star star-3" for="star-3"></label>

    <input onchange='this.form.submit();' class="star star-2" id="star-2" value="2" type="radio" name="star"  />
    <label class="star star-2" for="star-2"></label>

    <input onchange='this.form.submit();' class="star star-1" id="star-1" value="1" type="radio" name="star" checked/>

    <label class="star star-1" for="star-1"></label>


{% else %}
   <input onchange='this.form.submit();' class="star star-5" id="star-5" value="5" type="radio" name="star" />

    <label class="star star-5" for="star-5"></label>
    <input onchange='this.form.submit();' class="star star-4" id="star-4" value="4" type="radio" name="star" />

    <label class="star star-4" for="star-4"></label>

    <input onchange='this.form.submit();' class="star star-3" id="star-3" value="3" type="radio" name="star" />

    <label class="star star-3" for="star-3"></label>

    <input onchange='this.form.submit();' class="star star-2" id="star-2" value="2" type="radio" name="star"  />
    <label class="star star-2" for="star-2"></label>

    <input onchange='this.form.submit();' class="star star-1" id="star-1" value="1" type="radio" name="star" />

    <label class="star star-1" for="star-1"></label>
    
{% endif %}	
 

  </form>

</div>
<script src="{% static "/js/Droplist.js" %}"></script>
{% endblock %}

djangoproject/GoodReads/Books/templates/allauthor.html
{% extends 'base.html' %}
{% block title %} All Authors {% endblock %}
	{% block body %}
	{% if all_authors %}
		<h3>All Authors List:</h3>

		<ul>
			{% for author in all_authors  %}
			<li>
				<a href="/Books/{{ author.id }}/">{{ author.name }}  </a>
				<br><br>
			</li>
			{% endfor  %}
		</ul>
	{% else %}
		<h3>you don't have any authors yet ...</h3>
	{% endif %}
	{% endblock%}

djangoproject/GoodReads/Books/templates/allbooks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} All books {% endblock %}
{% block body %}
	{% if all_books %}
		<h3>All books List:</h3>

		<ul>
			{% for book in all_books  %}
			<div id="bookpic">
			<li>
				<img  src="/media/{{book.picture}}">
				<!-- <a href="/Books/{{ book.id }}/">{{ book.name }}  </a> -->
				<a href="{{book.id}}">{{ book.name }}  </a>
				<br><br><br><br><br><br>
			</li>
			</div>
			{% endfor  %}
		</ul>
	{% else %}
		<h3>you don't have any authors yet ...</h3>
	{% endif %}
{% endblock%}

djangoproject/GoodReads/Books/templates/authordetails.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Author Details {% endblock %}

	{% block body %}
	<div>
		<h2>Author Name: {{author.name}}</h2>
	</div>
	<div id="authorpic">
		<img src="/media/{{author.picture}}">
	</div>
	<div id="startdiv"> 
		<button  class="button" id='start' width='120' height = '120'>
			{% if author.is_followed %}
				followed
			{% else %}
				follow
			{% endif %}
		</button>
	</div>
	{% if error_message %}
		<p><strong>{{error_message}}</strong></p>
	{% endif %}
	<div id=booklist>
		<h3>All Author Books:</h3>
		<form action="{% url 'Books:favorite' author.id %}" method="post">
			{% csrf_token %}
			{% for book in bookss %}
				<input type="radio"  id="book{{ forloop.counter }}" name="bookk" value="{{book.id}}">
				<label for="book{{ forloop.counter }}">
					{{book.name}}
					{% if book.is_favorite %}
						<img src="/media/star" width='18' height = '18'/>
					{% endif %}
				</label><br>
			{% endfor %}
			<input class="button" id="favorite" type="submit" value="favorite" name="" >
		</form>
			<h5>{{ author.is_followed }}</h5>
	
<script src="{% static 'js/author.js'%}"></script>
{% endblock %}
</body>

djangoproject/GoodReads/Books/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

	<title>{% block title %}Tachyon {% endblock %}</title>
	<link rel="stylesheet"  href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family-Satisfy">
	<link rel="stylesheet" type="text/css" href="{% static 'css/author.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
	<!-- header -->
	<nav class="navbar navbar-inverse">
		<dir class="container-fluid">

			<!-- header -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#TopNavBar">
					 <span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'Books:index' %}">Tachyon</a>
			</div>

			<!-- items -->
			<div class="collapse navbar-collapse" id="TopNavBar">
				<ul class="nav navbar-nav">
					<li class="">
						<a href="{% url 'Books:allauthors' %}">
							<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
							Authors
						</a>
					</li>
					<li class="">
						<a href="{% url 'Books:allbooks' %}">
							<span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;
							Books
						</a>
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'Books:search' %}">
					<div class="form-group">
						<input type="text" class="form-control" name="q" value="">
					</div>
					<button type="submit" class="btn btn-default">Search</button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="{% url 'Books:index' %}">
							<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
							Logout
						</a>
					</li>
				</ul>

			</div>

		</dir>
	</nav>

 {% block body %}
 {% endblock %}
</body>
</html>

djangoproject/GoodReads/Books/templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block body %}
<link rel="stylesheet" href="{% static "/css/catimg.css" %}"/>
<h3>All Books in {{categoryName}} category are:</h3>
{% for book in selectedCategory %} 
<li>{{book}}</li>
<img src="/media/{{book.picture}}" id="book_img_cat"></img>
{% endfor %}

{% endblock %}

djangoproject/GoodReads/Books/templates/index.html
{% extends 'base.html' %}
{% block title %} GoodReads {% endblock %}
	{% block body %}
<h1>{{username}}</h1>
	<div id="authorpic">
		<img src="/media/GoodReads-Icon.png">
                 
	</div>
	{% endblock%}

djangoproject/GoodReads/Books/templates/registration.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
<p> {{username}} </p>
{% endblock %}

djangoproject/GoodReads/Books/templates/search.html
{% for book in books_list %}

    <img src="/media/{{book.picture}}" width="100" height="100">

    <h1>{{book.name}}</h1>

{% endfor %}

{% for author in authors_list %}

    <img src="/media/{{authors.picture}}" width="100" height="100">

    <h1>{{author.name}}</h1>

{% endfor %}

djangoproject/GoodReads/Books/templates/startUpPage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %} 
<center>
<form method="POST" action="{% url 'Books:myurl' user_id %}">
{% csrf_token %}
User name: <input type="text" name="username"></br></br>
Password: <input type="password" name="password"></br>

<div><span>

<button type="button">Sign Up</button></span>
<span><button type="submit" value="Login"> Login</button></span>
</div>
</form>
</center>
{% endblock %}

djangoproject/GoodReads/Books/templates/users.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
                        <img src="/media/{{user.picture}}" width="200" style="display : inline-block">
  
                        <h1 style="display : inline-block">{{user}}</h1>

        <br>
        <br>
        <table border="solid">
        {% for book in books%}
            <tr>
                <td>
                    <img src="/media/{{book.picture}}" width="100" height="100">
                </td>
                <td>
                    <h1>{{book.name}}</h1>
                </td>
                <td>
                    <h4>{{book.status}}</h4>
                </td>
                <td>
                    <h4 width="30">
                        {{book.rate}}
                    </h4>
                </td>
            </tr>
        {% endfor %}

        </table>
   {% endblock %}
   